name: CI

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
      - 'rules.txt'
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.4.0

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9.7"

      - run: python -m pip install --upgrade pip
      - run: pip install genpac
      - run: genpac --format pac --user-rule-from ./rules.txt --pac-proxy "SOCKS5 127.0.0.1:1080" > ./pac.txt

      - uses: josStorer/get-current-time@v2.1.1
        id: time
        with:
          format: yyyy-MM-DD

      - uses: EndBug/add-and-commit@v9.1.1
        if: github.event_name != 'pull_request'
        with:
          message: "chore: ${{ steps.time.outputs.formattedTime }} update pac.txt"
          add: pac.txt
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
